export const GET_FEATURED_REQUESTED = "GET_FEATURED_REQUESTED";
export const GET_FEATURED_SUCCESS = "GET_FEATURED_SUCCESS";
export const GET_FEATURED_FAILED = "GET_FEATURED_FAILED ";

export const GET_NEW_REQUESTED = "GET_NEW_REQUESTED";
export const GET_NEW_SUCCESS = "GET_NEW_SUCCESS";
export const GET_NEW_FAILED = "GET_NEW_FAILED ";

export const GET_SEARCH_REQUESTED = "GET_SEARCH_REQUESTED";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILED = "GET_SEARCH_FAILED ";

export const SET_SEARCH_VALUE = "SET_SEARCH_VALUE";
